- hosts: 172.16.25.19
  become: true
  vars:
    created_username: rchubugin

  tasks:
     - name: system update
       become: yes
       ansible.builtin.yum:
         name: '*'
         state: latest

     - name: Install MYSQL from remote source #original path https://dev.mysql.com/get/mysql80-community-release-el7-7.noarch.rpm but it was moved. new location could be found in wget output
       become: yes
       ansible.builtin.yum:
         name: https://repo.mysql.com//mysql80-community-release-el7-7.noarch.rpm
         state: present

     - name: Install MySQL server
       become: yes
       ansible.builtin.yum:
           name: mysql-server

     - name: Copy my.cnf
       ansible.builtin.copy:
           src: my.cnf
           dest: /etc/my.cnf
           owner: root
           group: root
           mode: '0644'

     - name: Ensure SELinux disable
       ansible.builtin.lineinfile:
         path: /etc/selinux/config
         regexp: '^SELINUX='
         line: SELINUX=disabled

     - name: Add limits soft
       ansible.builtin.lineinfile:
           path: /etc/security/limits.conf
           insertbefore: '# End of file'
           line: '*               soft    nofile            65535'
           create: yes

     - name: Add limits hard
       ansible.builtin.lineinfile:
           path: /etc/security/limits.conf
           insertbefore: '# End of file'
           line: '*               hard    nofile            65535'
           create: yes
           
     - name: Change 20-nproc.conf
       ansible.builtin.replace:
           path: /etc/security/limits.d/20-nproc.conf
           regexp: '4096$'
           replace: '40960'

     - name: Install GNOME Desktop
       become: yes
       ansible.builtin.yum:
           name: "@^GNOME Desktop"

     - name: Install Compatibility Libraries
       become: yes
       ansible.builtin.yum:
           name: "@Compatibility Libraries"

     - name: Upgrade libstdc++ packages
       ansible.builtin.yum:
           name: 'libstdc++'
           state: latest

     - name: Install i686 libs
       ansible.builtin.yum:
           name: "{{ packages }}"
       vars:
           packages:
             - libgcc*i686
             - libstdc++*i686
             - glibc*i686
             - libgfortran*i686
             - libaio*i686

     - name: Change default target to graphical.target
       ansible.builtin.file:
           src: /usr/lib/systemd/system/graphical.target
           dest: /etc/systemd/system/default.target
           state: link

     - name: Disable firewall
       ansible.builtin.service:
           name: firewalld
           state: stopped
           enabled: no
           masked: yes

     - name: Enable MySQL
       ansible.builtin.systemd:
             state: started
             name: mysqld
             enabled: yes